### ISSUE TITLE
Outsourced pcb manufacturing + assembly

### ISSUE THREAD

**Issue by cuong450** [taborlab/LPA-hardware#15]
Here are the issues mentioned by the outsourced company:

Thank you so much for your updated design, and we still have below issues:

1.#11_L1 p/n: VLS6045EX-151M does the orientation matter for this part?
 
[issue1_2 jpg](https://user-images.githubusercontent.com/15172848/27229032-fa494398-5277-11e7-9038-b892934466d1.jpeg)
![issue1_1 jpg](https://user-images.githubusercontent.com/15172848/27229033-fa68ccd6-5277-11e7-93ee-a7b23477ac0e.jpeg)

2. In your new Gerber, there is no negative pole marks any more. Please comment.(We know you don't need us the solder the parts on the top side, but we just remind.)

![issue2_1 jpg](https://user-images.githubusercontent.com/15172848/27229079-237e6356-5278-11e7-9549-f5034a213550.jpeg)

**Comment by KarlGerhardt** [comment]
Hi Cuong,

1. I believe inductors in general don't have polarity, but each pad of the component should be aligned and soldered with only a single pad on the PCB. This would be consistent with having the component's indicator "dot" over one pad or the other. Sebastian can you confirm?  

2. The orientation does matter. It should be visible in the front silkscreen as in the below image.

![image](https://user-images.githubusercontent.com/11169131/27236631-4d8f602e-528b-11e7-84ab-ae4b8ec8368a.png)

Cheers,
Karl

**Comment by castillohair** [comment]
Hi Coung,

1. As Karl said, the orientation of the inductor L1 does not matter.

2. I'm opening the gerber files directly and the polarity marks for the LEDs are there, specifically in file `lpa-F.SilkS.gto`. I used the program Gerbv version 2.6A, which is free to download. Screenshot below.

![image](https://user-images.githubusercontent.com/1529481/27244220-23e06280-52ab-11e7-88ff-8a19224ab97f.png)

I'm worried that if the manufacturing company can't see certain layers for some reason, then they might miss the polarity in certain components in which it matters. Can you check with the company that they can see the polarity in capacitors C3, C5, diode D49, and component X1?

Hope this helps.

**Comment by castillohair** [comment]
Cuong,

Did you ask about the polarity of the other components?

**Comment by castillohair** [comment]
Closed due to inactivity.
