### ISSUE TITLE
Outsourced pcb manufacturing + assembly # 2

### ISSUE THREAD

**Issue by cuong450** [taborlab/LPA-hardware#16]
Hi,
The pcbs manufacturing + assembly company has 2 more questions. Please see attached 

![screen shot 2017-06-20 at 12 05 08 pm](https://user-images.githubusercontent.com/15172848/27343609-6e7e097e-55b1-11e7-93f3-cd5b29d7c13c.png)

Thank you for your fast replies.

**Comment by castillohair** [comment]
1) Those holes don't need to be plated.

2) Yes you can trim off those texts.
