### ISSUE TITLE
step G of Page 51 of 78 instruction 

### ISSUE THREAD

**Issue by cuong450** [taborlab/LPA-hardware#20]
g. Make sure that the “Flash”, “Erase memory before programming”, and “Verify programmed content” checkboxes are activated, and click on the “Program” button. The messages “Erasing device... OK”, “Programming Flash...OK”, and “Verifying Flash...OK” should appear below.

![atmelscreenverifyflasherror](https://user-images.githubusercontent.com/15172848/28934139-d43c480c-784d-11e7-8e77-f7748202f353.jpg)
![atmelverifyflasherrorscreenshot2](https://user-images.githubusercontent.com/15172848/28934140-d43e53f4-784d-11e7-8720-efdf5a0498bf.png)

Hi, Please see the attached screen shot of errors. What do you suggest?

**Comment by castillohair** [comment]
How many times did you try? Sometimes programming just fails for no reason, but then it works the next time.

**Comment by castillohair** [comment]
Also, on the fuses tab, you need to select the option with "16K CK/14CK" instead of "1K CK/14CK". This change is necessary for the new board model that you're building (as opposed to the model that we published in the paper).

**Comment by cuong450** [comment]
after switching to "EXTXOSC_8MHZ_XX_16KCK_14CK_65MS"., I have tried it about 20 times now. In my past, certain SD cards are rejected by certain programming chips. Can you tell me the specific SD card brand that you are using? (I am using Kingston 16GB SD)

Do you have other suggestions?

**Comment by castillohair** [comment]
So switching to "EXTXOSC_8MHZ_XX_16KCK_14CK_65MS" did not change anything?

**Comment by cuong450** [comment]
It just worked with  "EXTXOSC_8MHZ_XX_16KCK_14CK_65MS" setting and removed SD card. Good to know

**Comment by castillohair** [comment]
Glad it worked.

**Comment by cuong450** [comment]
however, the error LED is on? what does this mean?

**Comment by cuong450** [comment]
I see that it says it means no SD card available, but I plugged SD card back in. and error still present.

**Comment by castillohair** [comment]
Did you push the reset button after inserting the SD card?

**Comment by cuong450** [comment]
Yes, but the SD card does not have anything on it at the moment.

Am I suppose to put the dc.text and gcal.text file + the downloaded program.lpf files on the SD card?
Only those specific 3 files and nothing more?

In any folder of any name?

**Comment by castillohair** [comment]
Yes. Those files should be in the SD card itself, not in a folder.
