### ISSUE TITLE
Maximal light intensity from LED source

### ISSUE THREAD

**Issue by cuong450** [taborlab/LPA-hardware#22]
Hi,
Do you have any measurements of the maximal light intensity from LED sources?

In the case that the LED source intensity is too weak, and our biological assay needs higher intensities, what do you recommend that we do? Is it true that there is a 17mA maximal drive current for each LED?

Is it possible to modify the pcbs board components so that there is more driving current for a higher intensity LED bulb?

**Comment by castillohair** [comment]
Hi,

The maximum intensity depends on the specific LEDs being used. If you wanna see examples, check the following papers: https://www.nature.com/articles/srep35363?WT.feed_name=subjects_biotechnology and http://msb.embopress.org/content/13/4/926?utm_source=TrendMD&utm_medium=cpc&utm_campaign=Mol_Syst_Biol_TrendMD_0.

Dot correction values (numbers in the dc.txt file) can increase the overall intensity of the LEDs. The maximum DC value that you can ever set is 63, though. In our experience, if you ever use dot correction values past 30 or 40, the board's temperature can increase to such levels that the cell culture will not grow appropriately. Most of our work has been performed at dot corrections lower than 10.
