### ISSUE TITLE
SD card socket

### ISSUE THREAD

**Issue by kleagsand** [taborlab/LPA-hardware#25]
I'm trying to order all these pieces from DigiKey but the SD card socket is obsolete, is there a different part number I can replace this with?

Thanks in advance

Keagan

**Comment by castillohair** [comment]
It seems like this one has the same soldering pad layout and could therefore work as a replacement: https://www.digikey.com/product-detail/en/amphenol-fci/10067847-001RLF/609-3956-2-ND/2283478
